# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy CI

on:
  push:
    branches: [gh_pages]
  pull_request:
    branches: [gh_pages]
  schedule:
    - cron: '0 12 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup yarn
        run: npm install -g yarn

      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Prepare dependencies
        run: |
          yarn
          yarn sync
        env:
          SWARM_OAUTH_TOKEN: ${{ secrets.SWARM_OAUTH_TOKEN }}

      - name: Build
        run: yarn bundle
        env:
          NEXT_PUBLIC_BASE_PATH: /swarm-checked-in

      - run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          BASE_BRANCH: main
